vim.keymap.set("i", "<UP>", "<C-o>gk", { silent = true })
vim.keymap.set("i", "<DOWN>", "<C-o>gj", { silent = true })
vim.keymap.set("n", "<UP>", "gk", { silent = true })
vim.keymap.set("n", "<DOWN>", "gj", { silent = true })
vim.keymap.set("n", "k", "gk", { silent = true })
vim.keymap.set("n", "j", "gj", { silent = true })
vim.keymap.set("i", "<C-h>", "<LEFT>", { silent = true })
vim.keymap.set("i", "<C-l>", "<RIGHT>", { silent = true })
vim.keymap.set("i", "<C-k>", "<C-o>gk", { silent = true })
vim.keymap.set("i", "<C-j>", "<C-o>gj", { silent = true })
vim.keymap.set("n", "L", ':w<CR> <BAR> :! pdflatex %:t<CR>', { silent = true })
vim.keymap.set("n", "H", ":nohlsearch<CR>")
vim.keymap.set("v", "<leader>t", ":!column -t -s '|' -o '|'<CR>", { silent = true })
vim.keymap.set('n', 'yy', '"+yy')
vim.keymap.set('n', 'dd', '"+dd')
vim.keymap.set('v', 'y', '"+y')
vim.keymap.set('v', 'd', '"+d')
