# vim:fileencoding=utf-8:foldmethod=marker

# Theme Catppuccin-Mocha
include current-theme.conf

font_size 15.0

# Scrollback
scrollback_lines 2000
scrollbar scrolled
scrollbar_interactive yes
scrollbar_jump_on_click yes

# Progress bar when OSC 9;4 escape equence is used
progress_bar top

# Launching applications when URL is clicked
open_url_with xdg-open

#Terminal bell
enable_audio_bell no

# Tab bar
tab_bar_edge bottom
tab_bar_style fade
tab_bar_align left
tab_bar_show_new_tab_button no
tab_switch_strategy previous
